### ISSUE TITLE
implement DASH

### ISSUE THREAD

**Issue by rshfsr** [nus-mmsys/tmf#4]
We need an application on top of TMF (Tiny Multimedia Framework) which creates DASH (Dynamic Adaptive Streaming over HTTP) segments and descriptions.

DASH is currently used in many multimedia application but to our knowledge there is no multimedia framework that can support it as a filter.

We need to create a filter for our framework that can support DASH.

**Comment by Murmur** [comment]
(is this a proper topic to discuss high level details about dash example) I have not compiled yet anything but wish to have a jump start before dive in.

This example11.cpp reads video4linux2 webcam, encodes 640x480 400Kbit 20fps stream. Output is a static infinitely growing raw videofile? Why is output name set to an encoder filter? It is not the last one in a pipeline.

Where is dashmanifest.mdp written or segment splitting done? is this still very early in progress so most things are missing? thx

**Comment by arashafiei** [comment]
Thanks for your comment.

Yes, example 11 is supposed to read webcam stream and store it on a file.

As you mention, it would be more logical to set the name of the file in the muxer instead of encoder. However, there were difficulties to separate completely the encoder and muxer. I will create a ticket for this issue that you mentioned.

As for DASH, nothing is implemented currently and this ticket is to build a filter for DASH. If you would like to participate, we really appreciate your help. You are free to add any filter.

**Comment by Murmur** [comment]
Yes it was a bit confusing to read read source code and think why is outputfile be given like it was. Maybe FileOutputFilter in the end where outputfile name is put. It would be like xxxSink gstreamer elements.

Dashing an existing mp4 videofiles is proven tech in MP4Box or similar tools but live feed would be very useful. Your TMF framework looks quite good actually after browsing source code. Maybe I could see what can do.

**Comment by arashafiei** [comment]
Great, thanks.

I was actually involved in building DashCast for MP4Box. As you say, dashing live feed will be very useful. TMF can have a filter to provide the functionality of DashCast. (only much cleaner and with filter design pattern)
